# Generated by Django 4.1.5 on 2023-01-17 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs", "0002_blog_clicked_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(related_name="blog_like", to=settings.AUTH_USER_MODEL),
        ),
    ]
